# Generated by Django 3.2 on 2023-07-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboards_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_update_date', models.DateTimeField(auto_now_add=True)),
                ('leaderboard_score', models.IntegerField(default=0)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboards.leaderboards')),
            ],
        ),
    ]
