# Generated by Django 4.2.3 on 2023-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=100)),
                ('lesson_description', models.TextField(max_length=1000)),
                ('lesson_content', models.TextField(max_length=10000)),
                ('lesson_style', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=0)),
            ],
        ),
    ]
