# Generated by Django 4.2.3 on 2023-08-01 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenges_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges_users", "0002_challenges_users_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="challenges_users",
            unique_together={("challenge", "user")},
        ),
    ]
