# Generated by Django 4.2.3 on 2023-08-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_description', models.TextField(max_length=1000)),
                ('unit_style', models.CharField(default='default', max_length=100)),
                ('unit_color', models.CharField(default='tiviElectricPurple', max_length=100)),
            ],
        ),
    ]
