# Generated by Django 4.2.3 on 2023-07-31 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("badges", "0001_initial"),
        ("badges_users", "0002_badges_users_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="badges_users",
            unique_together={("badge", "user")},
        ),
    ]
