# Generated by Django 3.2 on 2023-07-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boosters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boosters_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booster_start_date', models.DateTimeField(auto_now_add=True)),
                ('booster_end_date', models.DateTimeField(blank=True, null=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boosters.boosters')),
            ],
        ),
    ]
