# Generated by Django 4.2.3 on 2023-08-01 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boosters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("boosters_users", "0002_boosters_users_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="boosters_users",
            unique_together={("booster", "user")},
        ),
    ]
