# Generated by Django 4.2.3 on 2023-07-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boosters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booster_name", models.CharField(max_length=100)),
                ("booster_description", models.TextField(max_length=1000)),
                (
                    "booster_image",
                    models.ImageField(blank=True, upload_to="booster_images"),
                ),
                ("duration", models.IntegerField(default=0)),
                ("multiplier", models.IntegerField(default=1)),
            ],
        ),
    ]
