# Generated by Django 4.2.3 on 2023-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField(default=0)),
                ('streak_start_date', models.DateTimeField(auto_now_add=True)),
                ('streak_current_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('streak_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
