# Generated by Django 4.2.3 on 2023-08-01 13:08

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_challenges_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0001_initial"),
        ("ratings", "0002_ratings_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratings",
            name="rating_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ratings",
            unique_together={("user", "challenge", "task")},
        ),
    ]
