# Generated by Django 4.2.3 on 2023-07-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_description', models.TextField(max_length=1000)),
                ('folder_image', models.ImageField(blank=True, upload_to='folder_images')),
                ('folder_created', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('folder_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder')),
            ],
        ),
    ]
