# Generated by Django 4.2.3 on 2023-07-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folders",
            name="depth",
            field=models.IntegerField(default=0),
        ),
    ]
