# Generated by Django 4.2.3 on 2023-08-01 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resources",
            old_name="NotesPlaceHolder",
            new_name="notes_placeHolder",
        ),
    ]
