# Generated by Django 3.2 on 2023-07-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('challenges', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=100)),
                ('note_content', models.TextField(max_length=10000)),
                ('note_image', models.ImageField(blank=True, upload_to='note_images')),
                ('note_last_modified', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('note_average_rating', models.FloatField(default=0)),
                ('tags', models.TextField(default='', max_length=1000)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenges')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folders')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasks')),
            ],
        ),
    ]
