# Generated by Django 4.2.3 on 2023-07-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagues", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weak_date", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leagues.leagues",
                    ),
                ),
            ],
        ),
    ]
