# Generated by Django 4.2.3 on 2023-07-31 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaderboards", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboards",
            old_name="weak_date",
            new_name="week_date",
        ),
    ]
