# Generated by Django 4.2.3 on 2023-07-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
        ('lessons_users', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonUser',
            new_name='Lessons_Users',
        ),
    ]
